convert:
  - 
    type: 三餐
    shop: [
      浙西风味, 咖喱饭、盖浇饭, 自选餐, 西北面, 铁板烧, 粥吧, 湖南蒸菜, 石锅, 拉面,
      F牛肉饭, 茶泡饭, "猛咁人 港式烧腊", 老鸭粉丝汤, 汉堡,
    ]
    detail: true
  - 
    type: 三餐
    shop: [
      河西食堂一楼, 丽娃食堂一楼,
      沙县小吃（河西二楼）, 麻辣香锅（河西二楼）, 山东煎饼（河西二楼）,
      教工餐厅(河东), 麻辣香锅（河东二楼）, 麻辣烫(河东二楼), 炸鸡汉堡(河东二楼),
      伊源餐厅（丽娃二楼）,
    ]
  -
    type: 矿泉水
    shop: [五舍开水]
  - 
    type: 饮料
    shop: [悸动烧仙草（河西二楼）]
  -
    type: 清洁
    shop: [河西男浴室, 丽娃男浴室, ]
  - 
    type: 就诊
    shop: [普陀校医院]
  -
    type: 水电煤
    shop: [普陀校内宿舍]  # 宿舍门口刷电费
ignore: [普陀教育超市, 普陀全家便利店, 普陀灵吾便利, ]